### ISSUE TITLE
Out of Context answers

### ISSUE THREAD

**Issue by anushkayadav** [ruoccofabrizio/azure-open-ai-embeddings-qna#11]
I am getting out of context answers when I enter the prompt in the "OpenAI Semantic Answer" text box. 

<img width="1740" alt="Screenshot 2023-02-17 at 2 16 43 PM" src="https://user-images.githubusercontent.com/42323785/219663185-55a08ea6-0b47-4b85-9015-68b0d9fcaece.png">

Whereas If i make the question part of prompt in settings, I get the right one. 

<img width="1728" alt="Screenshot 2023-02-17 at 2 24 17 PM" src="https://user-images.githubusercontent.com/42323785/219663312-2f223ce5-c2df-4555-987c-3030cb9f384b.png">

**Comment by ruoccofabrizio** [comment]
You modified the default prompt, removing the placeholder for the question replacement.

Please revert back to:

Please reply to the question using only the information present in the text above. If you can't find it, reply 'Not in the text'.
Question: _QUESTION_
Answer:

**Comment by claudiausd** [comment]
hi @ruoccofabrizio,

sorry for the inconvenience, I have deployed this solution, and in the "settings" section I can only set the "Language" parameter.. In this thread I noticed instead that the associated screenshot shows the Openai parameters (temperature, token response length,... )
how can i reset these parameters from frontend?
Thanks in advance!
<img width="521" alt="Screenshot_3" src="https://user-images.githubusercontent.com/93835894/232734209-681a378c-38b6-44d4-ace3-4b1e8f4a4836.png">
