### ISSUE TITLE
No new embeddings generated - no error

### ISSUE THREAD

**Issue by EmanueleMeazzo** [ruoccofabrizio/azure-open-ai-embeddings-qna#14]
Hello,

I've been playing with this tool since the first release, however recently, after having rebased by repository on the latest commits here, I can't seem to add any embedding

When I click on "Compute Embeddings" , nothing happens, or better, the first time I restart everything from scratch the index gets created, and after that every other interaction finishes immediately without any error

This is the output of the docker terminal (latest images) for trying to add 3 embeddings

![image](https://user-images.githubusercontent.com/1709105/220997847-46d9a6e8-86c0-4c06-a656-75efab86ea20.png)

I see no errors anywhere, do you have any suggestions on where to search for the issue?
Everything worked perfectly before the new pages were added, and all the models are deployed on Azure OpenAI

**Comment by ruoccofabrizio** [comment]
I see the batch container exited with code 0. Please double-check what happened there.

**Comment by EmanueleMeazzo** [comment]
@ruoccofabrizio that was just the SAS token for the storage account that had expired, but I wasn't using the batch uploader or the document uploader so I didn't care; it just the "Add text to the knowledge base" feature that doesn't work
If I upload a document the embedding is created

Here is what I get when trying to add a Text (same as before, minus the quitting of the batch container)

![image](https://user-images.githubusercontent.com/1709105/221153564-3adaa2f5-4226-4cf9-8f07-9933f8dc0c1f.png)

When I add a single document, the API calls gets triggered and the embeddings added:

![image](https://user-images.githubusercontent.com/1709105/221153858-7106ed07-e412-4a53-97c5-a9fc1ff1e0e5.png)

**Comment by ruoccofabrizio** [comment]
try pulling again, please

**Comment by EmanueleMeazzo** [comment]
After updating the image I still get the same behaviour
When I insert a text longer than the token limit I get an error (in the terminal output only), but still no embeddings created for text regardless of the token length

![EmbeddingsFail](https://user-images.githubusercontent.com/1709105/221171015-f70af8a3-aee8-4376-b91c-637c097d0f9c.gif)
