### ISSUE TITLE
Batch Processing: QUEUE_NAME variable not found

### ISSUE THREAD

**Issue by neaorin** [ruoccofabrizio/azure-open-ai-embeddings-qna#21]
Hi,

I used the **Run everything locally in Docker** approach and tried to batch upload a bunch of PDFs.
I got an error about missing environment variable QUEUE_NAME.

[Looking at this file](https://github.com/ruoccofabrizio/azure-open-ai-embeddings-qna/blob/main/code/BatchStartProcessing/__init__.py), it seems like a storage queue is being used in batch processing.

I created a queue, added the key to .env and everything worked fine.

So I guess the docs might need an update.

Thanks

**Comment by ruoccofabrizio** [comment]
Thanks for the heads-up, added it in the README.
