### ISSUE TITLE
Batch upload does not seem to work

### ISSUE THREAD

**Issue by Python3-Pyro** [ruoccofabrizio/azure-open-ai-embeddings-qna#27]
I tried uploading a single 5 page pdf document via "Add documents in Batch". I get the prompt that 1 document is being upload and that this will happen asynchronously and will take time. However even after waiting for more than an hour I cannot see the converted file in Index Management. What am I doing wrong? All necessary components have been provisioned in Azure.

**Comment by ruoccofabrizio** [comment]
Have a look at your Azure Function logs.
