### ISSUE TITLE
Can I using Azure Redis to replace the default Redis on docker?

### ISSUE THREAD

**Issue by teo-ma** [ruoccofabrizio/azure-open-ai-embeddings-qna#30]
Hi ,

I would like to deploy this demo on Azure,so Can I using Azure Redis to replace the default Redis on docker?If so,would you share the guides how to config?

Thanks,
Teo

**Comment by lukaszog** [comment]
Hello, 
you mean Azure Cache for Redis?

**Comment by teo-ma** [comment]
Hello,Yes I would like to use Azure Cache for Redis enterprise tie as it can support vector data.

**Comment by ruoccofabrizio** [comment]
When deployed on Azure, you can configure the Env Variables as described here to point to a different Redis: [AppSetting](https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#configure-app-settings)
