### ISSUE TITLE
After the non-English document is processed, the embedding content is displayed as garbled

### ISSUE THREAD

**Issue by cyberflying** [ruoccofabrizio/azure-open-ai-embeddings-qna#33]
After the non-English document is processed, the embedding content is displayed as garbled.
In home page > Question and Answer Context section and "Index_Management" page, "content" column are garbled.

**Comment by ruoccofabrizio** [comment]
which language are you dealing with? Can you provide a screenshot to better understand? Thanks.

**Comment by cyberflying** [comment]
Chinese Simplified.
“Question and Answer Context”:
![11](https://user-images.githubusercontent.com/6263170/229455418-fa0fcbae-ef7a-40c8-93ce-7e66777aff70.png)

index page, content column:
![22](https://user-images.githubusercontent.com/6263170/229455445-8a2c21c2-f59f-407f-aa91-fb91d3c48b03.png)

**Comment by Li-Yanzhi** [comment]
@cyberflying  I found the issue was from requests module,  if a text blob file have content-type without charset (content-type=text/plain rather than content-type=text/plain; charset=utf-8) , then requests module will set encoding ISO-8859-1 for response object, then in UI you will see garbled text.

The resolution is to add charset for blob of text file when uploading.  some code as bellow:

- First add a function to add charset to content_type
```
import chardet
def get_content_type_with_encoding(content_type, bytes_data):
    # Add encoding to content_type to avoid requests module to set incorrect encoding of ISO-8859-1 for text (text/plain) and html (text/html) files
    if "text" in content_type:
        try:
            encoding = chardet.detect(bytes_data)['encoding']
            if(encoding.lower().startswith('utf-8')):
                return f"{content_type}; charset=utf-8"
            if(encoding.lower().startswith('utf-16')):
                return f"{content_type}; charset=utf-8"
            
            return f"{content_type}; charset={encoding}"
        except Exception as e:
            return content_type
    else:
        return content_type
```

- Then update function upload_text_and_embeddings() and main content in pages/01_Add_Document.py
```
#line 13
content_type = get_content_type_with_encoding('text/plain', st.session_state['doc_text'])
source_url = llm_helper.blob_client.upload_file(st.session_state['doc_text'], file_name=file_name, content_type=content_type)
...
#line 61
content_type = get_content_type_with_encoding(mimetypes.MimeTypes().guess_type(uploaded_file.name)[0], bytes_data)
...
#line 97
content_type = get_content_type_with_encoding(mimetypes.MimeTypes().guess_type(up.name)[0], bytes_data)
```

**Comment by cyberflying** [comment]
thanks @Li-Yanzhi and  @ruoccofabrizio ! I tested the released fix and it works fine!
