### ISSUE TITLE
Batch upload is not working as expected

### ISSUE THREAD

**Issue by Python3-Pyro** [ruoccofabrizio/azure-open-ai-embeddings-qna#35]
I tried uploading a single 5 page pdf document via "Add documents in Batch". I get the prompt that 1 document is being upload and that this will happen asynchronously and will take time. However even after waiting for more than an hour I cannot see the converted file in Index Management. What am I doing wrong? All necessary components have been provisioned in Azure. 

Below are logs of the error -
azure-open-ai-embeddings-qna-batch-1  | info: Function.BatchStartProcessing[1]
azure-open-ai-embeddings-qna-batch-1  |       Executing 'Functions.BatchStartProcessing' (Reason='This function was programmatically called via the host APIs.', Id=9f86e0ca-325c-461c-bf10-9391d9cce231)
azure-open-ai-embeddings-qna-batch-1  | fail: Function.BatchStartProcessing[3]
azure-open-ai-embeddings-qna-batch-1  |       Executed 'Functions.BatchStartProcessing' (Failed, Id=9f86e0ca-325c-461c-bf10-9391d9cce231, Duration=1ms)
azure-open-ai-embeddings-qna-batch-1  |       Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.BatchStartProcessing
azure-open-ai-embeddings-qna-batch-1  |        ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
azure-open-ai-embeddings-qna-batch-1  |       Exception: KeyError: 'QUEUE_NAME'
azure-open-ai-embeddings-qna-batch-1  |       Stack:   File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 357, in _handle__function_load_request
azure-open-ai-embeddings-qna-batch-1  |           func = loader.load_function(
azure-open-ai-embeddings-qna-batch-1  |         File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 44, in call
azure-open-ai-embeddings-qna-batch-1  |           return func(*args, **kwargs)
azure-open-ai-embeddings-qna-batch-1  |         File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/loader.py", line 132, in load_function
azure-open-ai-embeddings-qna-batch-1  |           mod = importlib.import_module(fullmodname)
azure-open-ai-embeddings-qna-batch-1  |         File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
azure-open-ai-embeddings-qna-batch-1  |           return _bootstrap._gcd_import(name[level:], package, level)
azure-open-ai-embeddings-qna-batch-1  |         File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
azure-open-ai-embeddings-qna-batch-1  |         File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

**Comment by ruoccofabrizio** [comment]
If you did not use the template for resource creation, please create a "doc-processing" queue in the Azure Storage account associated with your Azure Function as per [READme](https://github.com/ruoccofabrizio/azure-open-ai-embeddings-qna#run-everything-locally-in-docker-webapp--redis-stack--batch-processing)  Double check you also have an env variable named "QUEUE_NAME" with value "doc-processing"
