### ISSUE TITLE
Failed when using Azure Cache for Redis Enterprise to replace Redis on ACI 

### ISSUE THREAD

**Issue by teo-ma** [ruoccofabrizio/azure-open-ai-embeddings-qna#39]
Hello

I Created Azure Cache for Redis Enterprise with Search and Json Modules,and configure the app setting of Azure APP servcie, which I set the Redis endpoint,port(10000) and password.But it failed when running .throw the below errors.Any suggestions?
![iShot_2023-04-05_14 00 09](https://user-images.githubusercontent.com/16115524/229993895-c011d2dc-f41a-4d28-a93d-1e77078aec30.png)

Thanks,
Teo

**Comment by teo-ma** [comment]
I read the source code of demo,I found the redis port is  "6379" ,which has been biult on your docker image(
fruocco/oai-embeddings) ,but azure cache for redis enterprise only use the port "10000" ,so we need to biuld our own image as the redis port has not been configured as the app environment of demo's azure app service.Any suggestions would be so much appreciated.

**Comment by ruoccofabrizio** [comment]
hi @teo-ma , thanks for highlighting this issue with ACRE. Sounds like a problem in checking the modules available in the Redis instance. We should temporarily work around it while we get a solution at the product level. 
For the port, you can specify it in the environment without rebuilding the image. (REDIS_PORT)

**Comment by teo-ma** [comment]
Thanks @ruoccofabrizio for kindly comments.

I tested this demo locally with Azure Redis Enterprise, which selected Search Module.So would you give me some suggestions on which azure redis  modules I should select when creating Azure Redis Enterprise?

**Comment by ruoccofabrizio** [comment]
We identified an issue with LangChain and submitted a fix. As soon as it's merged, we'll upgrade the code accordingly. Thanks again for the heads up! @teo-ma

**Comment by ruoccofabrizio** [comment]
@teo-ma : The issue should be fixed as LangChain merged our changes. Please try again, setting the following ENV variables:

REDIS_ADDRESS=YOUR_AZURE_REDIS_ADDRESS
REDIS_PORT=10000
REDIS_PASSWORD=XXX
