### ISSUE TITLE
not support model 3.5 and 4

### ISSUE THREAD

**Issue by myh-st** [ruoccofabrizio/azure-open-ai-embeddings-qna#42]
I have tested the model gpt-35-turbo and gpt-4, both of these models are not supported? or just support text-davinci-003, is there a need to change models in actual use in the future?

<img width="920" alt="image" src="https://user-images.githubusercontent.com/37788058/230389824-5b8301c9-0f30-4e4a-9f0a-5d6621624ae8.png">

My Deployment Models

<img width="898" alt="image" src="https://user-images.githubusercontent.com/37788058/230392989-cb9b3cc6-7dbd-4246-a301-5f4e9b005e3d.png">

**Comment by myh-st** [comment]
My Deployment Models

<img width="992" alt="image" src="https://user-images.githubusercontent.com/37788058/230392804-e414bdad-fb82-4e29-9fba-704c70a59199.png">

**Comment by ruoccofabrizio** [comment]
hi @myh-st just released an update to be able to use Chat based models (like gpt 3.5 and gpt 4).
To use the solution with GPT 3.5 or GPT 4, please add an environment variable as described [Use the Repo with Chat based deployment (gpt-35-turbo or gpt-4-32k or gpt-4](https://github.com/ruoccofabrizio/azure-open-ai-embeddings-qna#use-the-repo-with-chat-based-deployment-gpt-35-turbo-or-gpt-4-32k-or-gpt-4)
