### ISSUE TITLE
How to increase answer length limit in azure-open-ai-embeddings-qna?

### ISSUE THREAD

**Issue by YeLiuXiang** [ruoccofabrizio/azure-open-ai-embeddings-qna#48]
I am using the azure-open-ai-embeddings-qna project  and have noticed that the answers are truncated after a certain number of characters. I would like to know where I can find the answer length limit and how to increase it. Can someone please tell me how to modify the limit and increase the maximum length of the answers? Thank you

**Comment by YeLiuXiang** [comment]
I have tested all modules and encountered the issue of answer length limitation in each module. Here are three examples:
         In the first module "Chat", I asked three questions, but the answers to all three questions were only two lines long. I estimated that the actual answer length should be about 4 times the currently displayed content. 
        In the second module "Conversation Data Extraction", I asked 7 questions, but the answer was truncated at the beginning of the fifth question. (If I click "execute tasks" again at this point, the returned answer may also be truncated at the third answer position, and the truncation position is different each time.) 
        In the third module "Document Summary", the answer was also truncated and only displayed 3 lines, but it should actually return about 5 lines of data.  
        I hope you can help to answer the next question, thank you very much

first module "Chat"
[pic1](https://github.com/YeLiuXiang/Moko_web/blob/master/picture/Image%206.png)

second module "Conversation Data Extraction"
[pic2](https://github.com/YeLiuXiang/Moko_web/blob/master/picture/Image%208.png)

 third module "Document Summary"
[pic3](https://github.com/YeLiuXiang/Moko_web/blob/master/picture/Image%209.png)

**Comment by YeLiuXiang** [comment]
To add to the new discovery, currently using the text-davinci model, if I ask it to generate a 200-word English article, it can generate the full 200 words. However, if I ask it to generate a 200-word Chinese article, it can only display the first 100 words, and the rest of the content is truncated and cannot be displayed.

**Comment by ruoccofabrizio** [comment]
Thanks for providing more info. I'll have a look at it and let you know.

**Comment by ruoccofabrizio** [comment]
@YeLiuXiang: Thanks for the feedback, can you please try again as the PR has just been approved?
