### ISSUE TITLE
Translation model is not working

### ISSUE THREAD

**Issue by krzysztofpaluszynski** [ruoccofabrizio/azure-open-ai-embeddings-qna#61]
Please help me to solve translation model problem and is there any settings to be checked.
Before deployment proces I add KEY 1 and endpoint: text translation (https://api.cognitive.microsofttranslator.com/).
How to fix this ?

Message:

Translation model is not working.
Please check your Azure Translator key in the App Settings.
Then restart your application.

Traceback (most recent call last): File "/usr/local/src/myscripts/OpenAI_Queries.py", line 41, in check_deployment llm_helper.translator.translate("This is a test", "it") File "/usr/local/src/myscripts/utilities/translator.py", line 36, in translate if (response[0]['language'] != language): KeyError: 0

<img width="890" alt="image" src="https://user-images.githubusercontent.com/126655390/234352369-5d97000e-a24d-4425-b544-f46940ce7b2e.png">

**Comment by ruoccofabrizio** [comment]
You need to add the Azure Translator region as well. Please read the instructions before opening issues.

**Comment by krzysztofpaluszynski** [comment]
I think that I put to this variable: West Europe in the script.
Would you be so kind and tell me where after AZURE script deployment I can double check this ?

TRANSLATE_REGION	YOUR_TRANSLATE_REGION

**Comment by krzysztofpaluszynski** [comment]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/126655390/234364117-1cd48d89-f8e3-406d-9bfe-bb9ad87a0912.png">

**Comment by ruoccofabrizio** [comment]
You can check it in the web app setting and in the batch function settings. The region value has to be exactly as stated in the Azure portal, for West Europe is "westeurope"
