### ISSUE TITLE
An option to delete document is not available

### ISSUE THREAD

**Issue by ArunPunjabi** [ruoccofabrizio/azure-open-ai-embeddings-qna#65]
Hi there,

I don't see an option to delete the documents uploaded on the portal. Would you be able to add an option to delete from Document Viewer? Please advise. 
I can see an option to delete from Index Management though, but it is not working.

Thanks,
Arun

**Comment by ArunPunjabi** [comment]
Hi! Is it feasible to have a session based chat where the documents should be deleted automatically once the session is over.

Thanks,
Arun

**Comment by ruoccofabrizio** [comment]
> Hi there,
> 
> I don't see an option to delete the documents uploaded on the portal. Would you be able to add an option to delete from Document Viewer? Please advise. I can see an option to delete from Index Management though, but it is not working.
> 
> Thanks, Arun

You can delete the files directly from Azure Blob Storage. The option in the Index Management deletes the embeddings related to that filename not the file itself.

**Comment by ruoccofabrizio** [comment]
> Hi! Is it feasible to have a session based chat where the documents should be deleted automatically once the session is over.
> 
> Thanks, Arun

Yes, you can create such behavior by combining the functionality already available in the code base.

**Comment by ArunPunjabi** [comment]
> > Hi there,
> > I don't see an option to delete the documents uploaded on the portal. Would you be able to add an option to delete from Document Viewer? Please advise. I can see an option to delete from Index Management though, but it is not working.
> > Thanks, Arun
> 
> You can delete the files directly from Azure Blob Storage. The option in the Index Management deletes the embeddings related to that filename not the file itself.
###############

That's right. However, anyone using the web link can view the documents from Document Viewer. Is it possible to hide/remove the documents from portal itself? (instead of deleting from Blob Storage). It would be super if you can implement that. Pls let me know. Thanks.
