### ISSUE TITLE
converts 2 pages of pdf into text file

### ISSUE THREAD

**Issue by Shubham-Kr10** [ruoccofabrizio/azure-open-ai-embeddings-qna#66]
On conversion of pdf to its corresponding text files it only converts first two pages of pdf

**Comment by ruoccofabrizio** [comment]
You are probably using the [Azure Form Recognizer free tier](https://learn.microsoft.com/en-us/azure/applied-ai-services/form-recognizer/service-limits?view=form-recog-3.0.0#model-usage) which is limited to 2 pages only.
