### ISSUE TITLE
change port

### ISSUE THREAD

**Issue by tekntrash** [ruoccofabrizio/azure-open-ai-embeddings-qna#68]
it seems to be harcoded to port 8080, how to change it to run on another such as the common port 80?

**Comment by ruoccofabrizio** [comment]
which method are you using to run the solution?

**Comment by tekntrash** [comment]
docker compose up

**Comment by ruoccofabrizio** [comment]
you can modify the docker compose yml file:

`version: "3.9"
services:
  web:
    image: fruocco/oai-embeddings
    ports:
      - "**8080**:80"
    env_file:
      - .env
    depends_on:
      api:
        condition: service_healthy`
