### ISSUE TITLE
DENY - - STORAGE ACCOUNT (Latest TLS version should be used in your storage account

### ISSUE THREAD

**Issue by vikramhn** [ruoccofabrizio/azure-open-ai-embeddings-qna#7]
![image](https://user-images.githubusercontent.com/17201365/217113972-39369f71-fda6-402d-beb7-d0a287f201fb.png)

**Comment by ruoccofabrizio** [comment]
This is a storage policy within your subscription. Please modify the ARM template to match the minimum version your organization mandates: 
Property of storage account to add:
            "minimumTlsVersion": "",
