### ISSUE TITLE
redis.exceptions.AuthenticationError: invalid username-password pair or user is disabled.

### ISSUE THREAD

**Issue by manel00** [ruoccofabrizio/azure-open-ai-embeddings-qna#72]
Hello,

When I run with  `docker-compose up` It appears the error from the title, How to fix the authentication for Redis?

Thank you

Regards

**Comment by ruoccofabrizio** [comment]
Check your .env file. If you don't need to enable authentication for local execution, remove the following parameters.

REDIS_PASSWORD=redis-stack-password
REDIS_ARGS=--requirepass $REDIS_PASSWORD
