### ISSUE TITLE
Unable to use "history" when calling the ApiQna function

### ISSUE THREAD

**Issue by briceglase** [ruoccofabrizio/azure-open-ai-embeddings-qna#84]
First, thanks for sharing this great work.
For some reason, I keep getting a 500 when executing the below on ApiQnA. Is there any obvious reason?
![image](https://github.com/ruoccofabrizio/azure-open-ai-embeddings-qna/assets/60719913/3aab8436-7832-41b0-9424-9696eb878f6b)
Here is the detailed error message I’m getting. Note that it works perfectly fine if I remove the “history” attribute from the Body.
![image](https://github.com/ruoccofabrizio/azure-open-ai-embeddings-qna/assets/60719913/922e3f4d-d481-4e23-9801-b02e09cde18b)

**Comment by ruoccofabrizio** [comment]
Hi, please pass a tuple as part of the history array in the body.

    'history': [
        ("question1", 'answer1')
        ]
