### ISSUE TITLE
Getting redis.exceptions.ResponseError: unknown command `MODULE`, with args beginning with: `LIST`

### ISSUE THREAD

**Issue by Shubham-Kr10** [ruoccofabrizio/azure-open-ai-embeddings-qna#90]
I have generated a redis url redis://:Primary Key from Azure Cache @Hostname for Azure cache:6379 
But after running code it gives  redis.exceptions.ResponseError: unknown command `MODULE`, with args beginning with: `LIST` in connection.py of redis library.
Any help will be thankfull.

**Comment by ecamaj** [comment]
It seems you need to generate ENTERPRISE cache type, which is by the way very expensive.

**Comment by ruoccofabrizio** [comment]
The solution uses RediSearch and RedisJson modules. You can find the modules for different SKUs here.

https://azure.microsoft.com/en-us/pricing/details/cache/
