### ISSUE TITLE
QNA API function doesn't seem to be working properly

### ISSUE THREAD

**Issue by divyansh-23906** [ruoccofabrizio/azure-open-ai-embeddings-qna#96]
Hi, the requests are getting 500 response.
![image](https://github.com/ruoccofabrizio/azure-open-ai-embeddings-qna/assets/96038236/02b0a4f8-ec90-4b69-bcb5-4707ca7b0aaf)
![image](https://github.com/ruoccofabrizio/azure-open-ai-embeddings-qna/assets/96038236/15873d40-0e9c-46da-93a3-7f2ff357d8ff)

**Comment by ruoccofabrizio** [comment]
Please check the Azure Function logs for more details

**Comment by divyansh-23906** [comment]
> Please check the Azure Function logs for more details

![image](https://github.com/ruoccofabrizio/azure-open-ai-embeddings-qna/assets/96038236/ecc4e92b-febf-41b4-9b03-b304081ea20a)

**Comment by ruoccofabrizio** [comment]
Check the value of OPENAI_ENGINE in the Azure Function env settings and set it to your Azure OpenAI deployment name.

**Comment by divyansh-23906** [comment]
Ok, after the APIQNA image update, I had to update the env settings of the function.
